In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

2022-01-21 21:14:43.769616: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-21 21:14:43.769636: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
(X_train, y_train), (X_test, y_test) = datasets.cifar10.load_data()
X_train.shape

(50000, 32, 32, 3)

In [8]:
print(X_train[0])

[[[0.23137255 0.24313725 0.24705882]
  [0.16862745 0.18039216 0.17647059]
  [0.19607843 0.18823529 0.16862745]
  ...
  [0.61960784 0.51764706 0.42352941]
  [0.59607843 0.49019608 0.4       ]
  [0.58039216 0.48627451 0.40392157]]

 [[0.0627451  0.07843137 0.07843137]
  [0.         0.         0.        ]
  [0.07058824 0.03137255 0.        ]
  ...
  [0.48235294 0.34509804 0.21568627]
  [0.46666667 0.3254902  0.19607843]
  [0.47843137 0.34117647 0.22352941]]

 [[0.09803922 0.09411765 0.08235294]
  [0.0627451  0.02745098 0.        ]
  [0.19215686 0.10588235 0.03137255]
  ...
  [0.4627451  0.32941176 0.19607843]
  [0.47058824 0.32941176 0.19607843]
  [0.42745098 0.28627451 0.16470588]]

 ...

 [[0.81568627 0.66666667 0.37647059]
  [0.78823529 0.6        0.13333333]
  [0.77647059 0.63137255 0.10196078]
  ...
  [0.62745098 0.52156863 0.2745098 ]
  [0.21960784 0.12156863 0.02745098]
  [0.20784314 0.13333333 0.07843137]]

 [[0.70588235 0.54509804 0.37647059]
  [0.67843137 0.48235294 0.16470588]


In [7]:
#normalizando variáveis
X_train = X_train / 255
X_test = X_test / 255
#transformando targets em um array de uma dimensão, para ficar mais simples de ler
y_train = y_train.reshape(-1, )

In [6]:
#criando rede neural comum
rna = keras.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    layers.Dense(3000, activation='relu'),
    layers.Dense(1000, activation='relu'),
    layers.Dense(10, activation='sigmoid')
])

rna.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])
rna.fit(X_train, y_train, epochs=5)

Epoch 1/5
1563/1563 [==============================] - 54s 35ms/step - loss: 1.8794 - accuracy: 0.3283
Epoch 2/5
1563/1563 [==============================] - 54s 35ms/step - loss: 1.6748 - accuracy: 0.3976
Epoch 3/5
1563/1563 [==============================] - 54s 34ms/step - loss: 1.5924 - accuracy: 0.4277
Epoch 4/5
1563/1563 [==============================] - 55s 35ms/step - loss: 1.5366 - accuracy: 0.4494
Epoch 5/5
1563/1563 [==============================] - 55s 35ms/step - loss: 1.5034 - accuracy: 0.4636


In [11]:
#criando rede neural convulacional
cnn = keras.Sequential([
    #CNN
    layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)), #strides = 2 
    layers.Conv2D(filters=32, activation='relu', kernel_size=(3,3), input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)), #strides = 2
    #NN
    keras.layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

cnn.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])
cnn.fit(X_train, y_train, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 12s 7ms/step - loss: 1.4949 - accuracy: 0.4653
Epoch 2/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.1537 - accuracy: 0.5954
Epoch 3/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.0311 - accuracy: 0.6407
Epoch 4/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.9549 - accuracy: 0.6675
Epoch 5/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.8935 - accuracy: 0.6891
Epoch 6/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.8477 - accuracy: 0.7055
Epoch 7/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.8052 - accuracy: 0.7182
Epoch 8/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.7684 - accuracy: 0.7317
Epoch 9/10
1563/1563 [==============================] - 11s 7ms/step - loss: 0.7374 - accuracy: 0.7405
Epoch 10/10
1563/1563 [==============================] - 11s 7ms/step - l